=== RatJuggler/developer-portfolio/src/main/webapp/data/skills-data-schema.json
{
  "$id": "https://developer-portfolio/interests-data-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Developer Portfolio Site Skills Data",
  "description": "Define the skills of the developer.",
  "type": "array",
  "minItems": 1,
  "maxItems": 999,
  "uniqueItems": true,
  "additionalProperties": false,
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": ["id", "level", "category", "skill", "description"],
    "properties": {
      "id": {
        "description": "A number to identify the individual interest.",
        "type": "integer"
      },
      "level": {
        "description": "The skill level.",
        "type": "string",
        "enum": ["Core", "Proficient", "Familiar"]
      },
      "category": {
        "description": "What category the skill comes under.",
        "type": "string",
        "minLength": 4,
        "maxLength": 64
      },
      "skill": {
        "description": "A brief description of the skill.",
        "type": "string",
        "minLength": 3,
        "maxLength": 64
      },
      "description": {
        "description": "A more detailed description of the skill.",
        "type": "string",
        "maxLength": 512
      }
    }
  }
}

=== RatJuggler/developer-portfolio/src/main/webapp/data/skills.json
[
  {
    "id": 1,
    "level": "Core",
    "category": "Server Side",
    "skill": "Java",
    "description": "The Java language up to version 11"
  },
  {
    "id": 2,
    "level": "Proficient",
    "category": "Server Side",
    "skill": "Python",
    "description": "The Python language up to version 3.x"
  },
  {
    "id": 3,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "JHipster",
    "description": "Application generation"
  },
  {
    "id": 4,
    "level": "Core",
    "category": "Server Side",
    "skill": "Java EE",
    "description": "Application framework up to version 8"
  },
  {
    "id": 5,
    "level": "Core",
    "category": "Server Side",
    "skill": "JPA",
    "description": "ORM using Hibernate and EclipseLink"
  },
  {
    "id": 6,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "EJB 3.x",
    "description": "Session beans with annotations"
  },
  {
    "id": 7,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Servlet",
    "description": "Basic service framework"
  },
  {
    "id": 8,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "JAX-RS",
    "description": "RESTful web services"
  },
  {
    "id": 9,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "JMS",
    "description": "Java Message Service"
  },
  {
    "id": 10,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "JTA",
    "description": "Java Transaction API"
  },
  {
    "id": 11,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "CDI",
    "description": "Context and Dependency Injection"
  },
  {
    "id": 12,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Bean Validation",
    "description": "Validation using annotations"
  },
  {
    "id": 13,
    "level": "Core",
    "category": "Server Side",
    "skill": "Spring Framework",
    "description": "Application framework"
  },
  {
    "id": 14,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Spring Boot",
    "description": "Create stand-alone Spring applications"
  },
  {
    "id": 15,
    "level": "Core",
    "category": "Server Side",
    "skill": "Spring MVC",
    "description": "MVC framework"
  },
  {
    "id": 16,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Spring Web Flow",
    "description": "Stateful business task processing"
  },
  {
    "id": 17,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Spring Data",
    "description": "Data access framework"
  },
  {
    "id": 18,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Spring Security",
    "description": "Authentication and access-control"
  },
  {
    "id": 19,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Spring Session",
    "description": "Container neutral web session"
  },
  {
    "id": 20,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Spring Web Services",
    "description": "XML web services"
  },
  {
    "id": 21,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Spring Roo",
    "description": "Application generation"
  },
  {
    "id": 22,
    "level": "Core",
    "category": "Server Side",
    "skill": "Spring Batch",
    "description": "Batch processing"
  },
  {
    "id": 23,
    "level": "Core",
    "category": "Server Side",
    "skill": "Spring Integration",
    "description": "Enterprise application integration"
  },
  {
    "id": 24,
    "level": "Core",
    "category": "Server Side",
    "skill": "XML",
    "description": "Document markup language"
  },
  {
    "id": 25,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "XSD",
    "description": "XML schema definition"
  },
  {
    "id": 26,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "XSLT",
    "description": "XML transform language"
  },
  {
    "id": 27,
    "level": "Core",
    "category": "Server Side",
    "skill": "JSON",
    "description": "Data interchange format"
  },
  {
    "id": 28,
    "level": "Familiar",
    "category": "Server Side",
    "skill": "Thymeleaf",
    "description": "HTML templating engine"
  },
  {
    "id": 29,
    "level": "Core",
    "category": "Continuous Integration",
    "skill": "Git",
    "description": "Distributed version control"
  },
  {
    "id": 30,
    "level": "Core",
    "category": "Continuous Integration",
    "skill": "Apache Subversion",
    "description": "Centralized version control"
  },
  {
    "id": 31,
    "level": "Core",
    "category": "Continuous Integration",
    "skill": "JUnit",
    "description": "Unit testing framework"
  },
  {
    "id": 32,
    "level": "Core",
    "category": "Continuous Integration",
    "skill": "Mockito",
    "description": "Mock object testing framework"
  },
  {
    "id": 33,
    "level": "Core",
    "category": "Continuous Integration",
    "skill": "Apache Maven",
    "description": "Dependency management build tool"
  },
  {
    "id": 34,
    "level": "Familiar",
    "category": "Continuous Integration",
    "skill": "Gradle",
    "description": "Dependency management build tool"
  },
  {
    "id": 35,
    "level": "Core",
    "category": "Continuous Integration",
    "skill": "Jenkins",
    "description": "Automated building, testing and deploy"
  },
  {
    "id": 36,
    "level": "Core",
    "category": "Continuous Integration",
    "skill": "SonarQube",
    "description": "Code quality control"
  },
  {
    "id": 37,
    "level": "Familiar",
    "category": "Continuous Integration",
    "skill": "Nexus",
    "description": "Repository Manager"
  },
  {
    "id": 38,
    "level": "Familiar",
    "category": "Continuous Integration",
    "skill": "Liquibase",
    "description": "Database schema change management"
  },
  {
    "id": 39,
    "level": "Core",
    "category": "Middleware",
    "skill": "WebSphere",
    "description": "Enterprise Application Server"
  },
  {
    "id": 40,
    "level": "Core",
    "category": "Middleware",
    "skill": "WebLogic",
    "description": "Enterprise Application Server"
  },
  {
    "id": 41,
    "level": "Core",
    "category": "Middleware",
    "skill": "Apache Tomcat",
    "description": "Servlet container"
  },
  {
    "id": 42,
    "level": "Familiar",
    "category": "Middleware",
    "skill": "Apache HTTP Server",
    "description": "Web server"
  },
  {
    "id": 43,
    "level": "Familiar",
    "category": "Middleware",
    "skill": "GlassFish",
    "description": "Java EE Reference implementation"
  },
  {
    "id": 44,
    "level": "Familiar",
    "category": "Middleware",
    "skill": "Open Liberty",
    "description": "WebSphere lite"
  },
  {
    "id": 45,
    "level": "Core",
    "category": "Middleware",
    "skill": "IBM MQ",
    "description": "Message Queues"
  },
  {
    "id": 46,
    "level": "Proficient",
    "category": "Middleware",
    "skill": "Docker",
    "description": "PaaS containers"
  },
  {
    "id": 47,
    "level": "Proficient",
    "category": "Middleware",
    "skill": "Nginx",
    "description": "Web server, proxy and load balancing"
  },
  {
    "id": 48,
    "level": "Proficient",
    "category": "Middleware",
    "skill": "Node.js",
    "description": "Server side JavaScript"
  },
  {
    "id": 49,
    "level": "Core",
    "category": "Relational",
    "skill": "SQL",
    "description": "Structured Query Language"
  },
  {
    "id": 50,
    "level": "Core",
    "category": "Relational",
    "skill": "DDL",
    "description": "Tables, views and stored procedures"
  },
  {
    "id": 51,
    "level": "Core",
    "category": "Relational",
    "skill": "Oracle DB",
    "description": "Oracle Enterprise RDBMS"
  },
  {
    "id": 52,
    "level": "Familiar",
    "category": "Relational",
    "skill": "Oracle DB XE",
    "description": "Developer version"
  },
  {
    "id": 53,
    "level": "Core",
    "category": "Relational",
    "skill": "MS SQL Server",
    "description": "Microsoft RDBMS"
  },
  {
    "id": 54,
    "level": "Core",
    "category": "Relational",
    "skill": "MySQL",
    "description": "Open-source RDBMS"
  },
  {
    "id": 55,
    "level": "Familiar",
    "category": "Relational",
    "skill": "PostgreSQL",
    "description": "Open-source RDBMS"
  },
  {
    "id": 56,
    "level": "Core",
    "category": "Client Side",
    "skill": "HTML",
    "description": "HTML5 and SVG"
  },
  {
    "id": 57,
    "level": "Core",
    "category": "Client Side",
    "skill": "CSS",
    "description": "Cascading Style Sheets"
  },
  {
    "id": 58,
    "level": "Core",
    "category": "Client Side",
    "skill": "JavaScript",
    "description": "ECMAScript"
  },
  {
    "id": 59,
    "level": "Familiar",
    "category": "Client Side",
    "skill": "Bootstrap",
    "description": "CSS framework"
  },
  {
    "id": 60,
    "level": "Familiar",
    "category": "Client Side",
    "skill": "jQuery",
    "description": "JavaScript library"
  },
  {
    "id": 61,
    "level": "Proficient",
    "category": "Client Side",
    "skill": "TypeScript",
    "description": "Strictly typed JavaScript"
  },
  {
    "id": 62,
    "level": "Proficient",
    "category": "Legacy",
    "skill": "J2EE",
    "description": "Application framework"
  },
  {
    "id": 63,
    "level": "Proficient",
    "category": "Legacy",
    "skill": "EJB 2.x",
    "description": "Session beans defined using XML"
  },
  {
    "id": 64,
    "level": "Familiar",
    "category": "Legacy",
    "skill": "JSP",
    "description": "Java Server Pages, HTML templating"
  },
  {
    "id": 65,
    "level": "Familiar",
    "category": "Legacy",
    "skill": "JSTL",
    "description": "JSP Standard Tag Library"
  },
  {
    "id": 66,
    "level": "Familiar",
    "category": "Legacy",
    "skill": "JSF",
    "description": "Java Server Faces"
  },
  {
    "id": 67,
    "level": "Familiar",
    "category": "Legacy",
    "skill": "Apache Struts",
