=== RatJuggler/developer-portfolio/shared-resources/src/main/resources/data/interests-data-schema.json
{
  "$id": "https://developer-portfolio/interests-data-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Developer Portfolio Site Interests Data",
  "description": "Define the interests of the developer.",
  "type": "array",
  "minItems": 1,
  "maxItems": 99,
  "uniqueItems": true,
  "additionalProperties": false,
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": ["id", "title", "imagePath", "description"],
    "properties": {
      "_classMap": {
        "description": "Spring Data deserializer class for the simple-service.",
        "type": "string",
        "maxLength": 64
      },
      "_classSQL": {
        "description": "Spring Data deserializer class for the sql-service.",
        "type": "string",
        "maxLength": 64
      },
      "id": {
        "description": "A number to identify the individual interest.",
        "type": "integer"
      },
      "title": {
        "description": "A brief description of the interest.",
        "type": "string",
        "minLength": 4,
        "maxLength": 64
      },
      "imagePath": {
        "description": "Path to an image for this interest.",
        "type": "string",
        "maxLength": 2048
      },
      "description": {
        "description": "A more detailed description of the interest.",
        "type": "string",
        "maxLength": 512
      }
    }
  }
}

=== RatJuggler/developer-portfolio/public/json/interests.json
[
  {
    "_classMap": "com.portfolio.map.domain.Interest",
    "_classSQL": "com.portfolio.sql.domain.Interest",
    "id": 1,
    "title": "Dinosaurs",
    "imagePath": "/img/Dinosaurs.jpg",
    "description": "I always wanted to be a paleontologist and though I ended up in IT they continue to fascinate me, I even built my own \"Dinosaur Of The Day\" twitter bot (@dinosauria_bot)."
  },
  {
    "_classMap": "com.portfolio.map.domain.Interest",
    "_classSQL": "com.portfolio.sql.domain.Interest",
    "id": 2,
    "title": "Video Games",
    "imagePath": "/img/VideoGames.jpg",
    "description": "I like playing video games and enjoy the variety and novelty of the environments they are often set in, as well as the ways they try to evolve and tell stories."
  },
  {
    "_classMap": "com.portfolio.map.domain.Interest",
    "_classSQL": "com.portfolio.sql.domain.Interest",
    "id": 3,
    "title": "History",
    "imagePath": "/img/History.jpg",
    "description": "I love reading about history, from Ancient Egypt and the Romans to the Medieval Ages, the English Civil War through to the Georgian era and the start of the industrial revolution."
  },
  {
    "_classMap": "com.portfolio.map.domain.Interest",
    "_classSQL": "com.portfolio.sql.domain.Interest",
    "id": 4,
    "title": "Maker Culture",
    "imagePath": "/img/MakerPi.jpg",
    "description": "Nothing more fun than fiddling with a Raspberry Pi, a soldering iron and some LEDs or trying to make a tensegrity structure. I have so far resisted the temptations of a 3D printer."
  },
  {
    "_classMap": "com.portfolio.map.domain.Interest",
    "_classSQL": "com.portfolio.sql.domain.Interest",
    "id": 5,
    "title": "Space",
    "imagePath": "/img/Space.jpg",
    "description": "Space is big. You just won't believe how vastly, hugely, mind-bogglingly big it is. I mean, you may think it's a long way down the road to the chemist's, but that's just peanuts to space‚Äù."
  }
]
