=== RatJuggler/developer-portfolio/shared-resources/src/main/resources/data/profile-data-schema.json
{
  "$id": "https://developer-portfolio/interests-data-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Developer Portfolio Site Profile Data",
  "description": "Define the profile of the developer.",
  "type": "object",
  "additionalProperties": false,
  "required": ["id", "name", "location", "status", "avatarPath", "photoPath", "description", "email", "linkedin", "github", "twitter"],
  "properties": {
    "_classMap": {
      "description": "Spring Data deserializer class for the map-service.",
      "type": "string",
      "maxLength": 64
    },
    "_classSQL": {
      "description": "Spring Data deserializer class for the sql-service.",
      "type": "string",
      "maxLength": 64
    },
    "id": {
      "description": "A number to identify the individual profile.",
      "type": "integer"
    },
    "name": {
      "description": "The developers name.",
      "type": "string",
      "minLength": 4,
      "maxLength": 128
    },
    "location": {
      "description": "The developers general location.",
      "type": "string",
      "minLength": 4,
      "maxLength": 128
    },
    "status": {
      "description": "The developers availability.",
      "type": "string",
      "enum": ["Available", "Unavailable"]
    },
    "avatarPath": {
      "description": "Path to an avatar image.",
      "type": "string",
      "maxLength": 128
    },
    "photoPath": {
      "description": "Path to a photo.",
      "type": "string",
      "maxLength": 128
    },
    "description": {
      "description": "Short bio of the developer.",
      "type": "string",
      "maxLength": 512
    },
    "email": {
      "description": "Email address.",
      "type": "string",
      "maxLength": 256
    },
    "linkedin": {
      "description": "Linkedin URL.",
      "type": "string",
      "maxLength": 2048
    },
    "github": {
      "description": "GitHub URL.",
      "type": "string",
      "maxLength": 2048
    },
    "twitter": {
      "description": "Twitter URL.",
      "type": "string",
      "maxLength": 2048
    }
  }
}

=== RatJuggler/developer-portfolio/public/json/profile.json
{
  "_classMap": "com.portfolio.map.domain.Profile",
  "_classSQL": "com.portfolio.sql.domain.Profile",
  "id": 1,
  "name": "John Chase",
  "location": "Smallfield, Surrey, England",
  "status": "Available",
  "avatarPath": "/img/Rat-Profile.svg",
  "photoPath": "/img/Photo.jpg",
  "description": "I am a Senior Developer with extensive SDLC experience. I have a proven track record of delivering bespoke solutions to meet demanding customer needs and growing those solutions to keep up with a changing market. I enjoy collaborating with a diverse team to build and promote a good working environment geared at delivering high-quality solutions.\n\nSelect one of the tabs to find out more about me.",
  "email": "john.chase3@outlook.com",
  "linkedin": "https://www.linkedin.com/in/john-chase-57973b12/",
  "github": "https://github.com/RatJuggler",
  "twitter": "https://twitter.com/ratjuggler"
}
